/* Questões autorais de Inglês — Modal verbs. */

export const questoes = [
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"You ___ wear a seatbelt in this country — it's the law.\" Complete with the modal that expresses obligation:",
    opcoes: ["must", "might", "could", "may", "would"],
    correta: 0,
    explicacao: "\"Must\" expressa obrigação forte, especialmente quando ligada a uma lei ou regra externa — coerente com \"it's the law\". \"Might/may/could\" expressam possibilidade, não obrigação, e não combinam com o contexto legal da frase.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ smoke inside the building — it's strictly forbidden.\" Complete with the modal that expresses prohibition:",
    opcoes: ["don't have to", "must not", "may not always", "could hardly", "should rarely"],
    correta: 1,
    explicacao: "\"Must not\" expressa proibição absoluta, coerente com \"strictly forbidden\". Já \"don't have to\" expressa ausência de obrigação (a pessoa pode fazer ou não), sentido bem diferente de proibição — uma confusão muito cobrada em provas de inglês.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ finish the whole report today — tomorrow is also fine.\" Complete with the modal that expresses absence of obligation:",
    opcoes: ["mustn't", "shouldn't", "don't have to", "can't", "won't"],
    correta: 2,
    explicacao: "\"Don't have to\" indica que a ação não é obrigatória, mas continua permitida — coerente com \"tomorrow is also fine\". \"Mustn't\", ao contrário, indicaria proibição, sentido oposto ao da frase.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"She isn't answering her phone. She ___ be asleep already.\" Complete with the modal that expresses a logical deduction:",
    opcoes: ["can", "shall", "will", "must", "need"],
    correta: 3,
    explicacao: "\"Must\", nesse contexto, não expressa obrigação, e sim uma dedução lógica forte a partir de evidências (não atender o telefone sugere que está dormindo). É um dos usos mais avançados dos modais, diferente do sentido de obrigação visto em outras questões.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"He left home two hours ago. He ___ be here by now.\" Complete with the modal that expresses probability:",
    opcoes: ["mustn't", "shouldn't", "needn't", "can't", "should"],
    correta: 4,
    explicacao: "\"Should\", nesse uso, expressa expectativa ou probabilidade (o que é razoável esperar), e não obrigação — \"ele já deveria estar aqui\", com base no tempo decorrido. É diferente do \"should\" de conselho, mas segue a mesma lógica de algo esperado.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"You look exhausted. You ___ get some rest.\" Complete with the modal that expresses advice:",
    opcoes: ["should", "must", "can", "will", "shall"],
    correta: 0,
    explicacao: "\"Should\" é o modal clássico de conselho, mais suave que \"must\" (obrigação). Dizer que alguém parece exausto e sugerir descanso é um conselho, não uma ordem — por isso \"should\" é mais adequado que \"must\" aqui.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"___ you help me carry these boxes, please?\" Complete with the modal used for a polite request:",
    opcoes: ["Must", "Could", "Need", "Should", "Shall"],
    correta: 1,
    explicacao: "\"Could\" é amplamente usado para pedidos educados, mais formal e suave que \"can\". \"Must\" soaria como uma ordem, e \"should\" sugeriria conselho, não pedido — nenhum dos dois se encaixa no tom cortês da frase.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"___ I open the window? It's a bit hot in here.\" Complete with the modal used to offer or ask permission:",
    opcoes: ["Must", "Would", "Shall", "Should", "Need"],
    correta: 2,
    explicacao: "\"Shall I...?\" é uma estrutura fixa usada para oferecer-se para fazer algo ou pedir instruções educadamente, comum no inglês britânico. \"Must I...?\" soaria estranho e excessivamente formal/negativo nesse contexto de oferta simples.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"When I was a child, I ___ climb trees in my backyard.\" Complete with the modal that expresses a past ability/habit:",
    opcoes: ["must", "should", "would", "could", "shall"],
    correta: 3,
    explicacao: "\"Could\" expressa habilidade geral no passado — algo que a pessoa era capaz de fazer quando criança. \"Would\" também indica hábito passado, mas geralmente para ações repetidas (não capacidades), o que torna \"could\" a escolha mais precisa aqui.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"Every summer, my grandfather ___ take us fishing at the lake.\" Complete with the modal that expresses a repeated past habit (not ability):",
    opcoes: ["can", "must", "should", "need", "would"],
    correta: 4,
    explicacao: "\"Would\" descreve um hábito repetido no passado, como uma lembrança de rotina — diferente de \"could\", que indica capacidade. \"Every summer\" reforça a ideia de repetição ao longo do tempo, não de uma habilidade isolada.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"It ___ rain later, but I'm not completely sure.\" Complete with the modal that expresses weak possibility:",
    opcoes: ["might", "must", "should", "have to", "shall"],
    correta: 0,
    explicacao: "\"Might\" expressa possibilidade fraca, incerta — coerente com \"but I'm not completely sure\". \"Must\" seria uma conclusão forte demais, e \"should\" indicaria expectativa razoável, não mera possibilidade.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"He ___ be at work now — I just saw his car in the driveway.\" Complete with the modal that expresses a logical impossibility:",
    opcoes: ["mustn't", "can't", "shouldn't", "needn't", "won't"],
    correta: 1,
    explicacao: "\"Can't\", nesse uso, expressa uma conclusão de que algo é logicamente impossível, a partir de uma evidência contrária (o carro está na garagem, então ele não pode estar no trabalho). É o oposto de \"must\" para dedução — \"must\" conclui que algo É verdade, \"can't\" conclui que algo NÃO É.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"___ you speak French?\" Complete with the modal used to ask about ability:",
    opcoes: ["Must", "Should", "Can", "Shall", "Would"],
    correta: 2,
    explicacao: "\"Can\" é o modal padrão para expressar e perguntar sobre habilidade — a capacidade de falar francês. \"Must\" indicaria obrigação, sentido completamente diferente de capacidade.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ better see a doctor about that cough.\" Complete with the fixed modal expression for strong advice:",
    opcoes: ["must", "could", "should", "had", "would"],
    correta: 3,
    explicacao: "\"Had better\" é uma expressão fixa que dá um conselho forte, quase um aviso, geralmente com implicação de consequência ruim se não for seguido. É mais enfático que \"should\", mas não chega a ser uma ordem como \"must\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You needn't have brought a gift — it really wasn't necessary.\" O uso de \"needn't have + particípio\" indica que a ação:",
    opcoes: ["era proibida", "foi feita e era obrigatória", "não foi feita e ainda é necessária", "será feita no futuro", "foi feita, mas era desnecessária"],
    correta: 4,
    explicacao: "\"Needn't have + particípio\" descreve uma ação que foi realizada, mas que, olhando em retrospecto, não era necessária — a pessoa trouxe o presente, mas não precisava ter trazido. É diferente de \"didn't need to\", que apenas indica que algo não era necessário, sem confirmar se foi feito.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ have called me — I was worried sick when you didn't show up.\" Complete with the modal expressing a criticism about a past action that wasn't done:",
    opcoes: ["could", "can", "may", "shall", "will"],
    correta: 0,
    explicacao: "\"Could have + particípio\" pode expressar uma crítica branda sobre algo que era possível fazer no passado, mas não foi feito — \"você poderia ter ligado\" (e não ligou). É uma estrutura de modal + perfeito usada para lamentar ou criticar o passado.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You should have studied harder for the test.\" A estrutura \"should have + particípio\" indica que a ação:",
    opcoes: ["ainda vai acontecer", "não aconteceu, e foi um erro não fazê-la", "aconteceu como esperado", "é proibida", "aconteceu por acaso"],
    correta: 1,
    explicacao: "\"Should have + particípio\" expressa arrependimento ou crítica sobre uma ação que não aconteceu no passado, mas deveria ter acontecido — a pessoa não estudou o suficiente, e isso é apontado como um erro. É uma das estruturas mais cobradas envolvendo modais e o particípio passado.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ not have worried — everything turned out fine.\" Complete with the modal expressing that a past action was unnecessary:",
    opcoes: ["must", "should", "need", "can", "shall"],
    correta: 2,
    explicacao: "\"Need not have + particípio\" (\"needn't have worried\") indica que a preocupação foi desnecessária, já que tudo deu certo. É a mesma estrutura vista com o presente do gift, aplicada aqui à ideia de preocupação.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"May I use your bathroom, please?\" O modal \"may\", nessa frase, expressa:",
    opcoes: ["obrigação", "hábito passado", "dedução lógica", "pedido educado de permissão", "proibição"],
    correta: 3,
    explicacao: "\"May\" é usado, entre outras funções, para pedir permissão de forma educada e formal — \"posso usar seu banheiro?\". É uma alternativa mais formal a \"can I\", frequentemente associada a contextos de cortesia.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"Students ___ bring their own laptops to the exam; the school provides them.\" Complete with the modal that expresses prohibition or lack of permission:",
    opcoes: ["shouldn't necessarily", "don't have to", "needn't", "would not", "may not"],
    correta: 4,
    explicacao: "\"May not\" indica que algo não é permitido — os alunos não têm permissão para trazer seus próprios notebooks, já que a escola os fornece. É diferente de \"don't have to\", que apenas indicaria ausência de obrigação, sem proibir a ação.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"Passengers ___ fasten their seatbelts before takeoff.\" Complete with the modal used in formal rules and regulations:",
    opcoes: ["shall", "can", "would", "might", "used to"],
    correta: 0,
    explicacao: "\"Shall\", em textos formais e regulamentos (manuais de avião, contratos, leis), expressa uma obrigação forte e impessoal — equivalente a \"must\" nesse registro específico. É um uso menos comum na fala cotidiana, mas recorrente em textos institucionais cobrados em provas.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"I ___ swim when I was five years old.\" Complete with the modal expressing past ability:",
    opcoes: ["should", "could", "would", "must", "shall"],
    correta: 1,
    explicacao: "\"Could\" é o modal padrão para habilidade no passado — a capacidade de nadar aos cinco anos. \"Would\" não se aplica aqui porque o verbo \"swim\" descreve uma habilidade, não uma ação habitual repetida.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"You don't ___ to bring anything to the party — we have everything covered.\" Complete with the modal expressing absence of necessity:",
    opcoes: ["must", "should", "need", "would", "shall"],
    correta: 2,
    explicacao: "\"Don't need to\" indica que uma ação não é necessária — não é preciso trazer nada para a festa. \"Must\" não combina com \"don't\" nesse sentido de necessidade (a negativa de \"must\" muda completamente de sentido, indicando proibição).",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You mustn't touch that wire — it's dangerous!\" O modal \"mustn't\", nessa frase, expressa:",
    opcoes: ["ausência de necessidade", "possibilidade", "conselho fraco", "proibição", "hábito"],
    correta: 3,
    explicacao: "\"Mustn't\" (must not) expressa proibição — não se deve, sob hipótese alguma, tocar no fio. É diferente de \"don't have to\", que indicaria apenas que a ação não é obrigatória, mas continuaria permitida.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You look pale — you ___ see a doctor immediately.\" Complete with the modal that expresses urgent, strong advice bordering on obligation:",
    opcoes: ["might", "could", "shall", "would", "must"],
    correta: 4,
    explicacao: "\"Must\", nesse contexto informal, pode expressar um conselho muito forte, quase uma obrigação, dada a urgência da situação (a pessoa está pálida). É mais enfático que \"should\", refletindo a gravidade percebida do estado de saúde.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"___ you mind closing the door? It's a bit cold.\" Complete with the modal used in a very polite request:",
    opcoes: ["Would", "Should", "Must", "Shall", "Need"],
    correta: 0,
    explicacao: "\"Would you mind...?\" é uma das estruturas mais educadas para fazer pedidos em inglês, seguida de verbo com -ing. É ainda mais formal que \"could you\", comum em situações que exigem delicadeza.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"I ___ help you with your homework if you want.\" Complete with the modal used to offer help:",
    opcoes: ["must", "can", "should", "need", "shall"],
    correta: 1,
    explicacao: "\"Can\", além de habilidade, também é usado para oferecer ajuda de forma simples e direta — \"posso te ajudar\". É um uso comum e informal, diferente da formalidade de \"shall I help you?\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"There's no answer at the door. They ___ be out.\" Complete with the modal that expresses a probable conclusion:",
    opcoes: ["needn't", "mustn't", "must", "shan't", "wouldn't"],
    correta: 2,
    explicacao: "\"Must\", de novo em seu uso dedutivo, conclui que algo é provavelmente verdade a partir de evidências — ninguém atende à porta, logo devem estar fora. É a mesma lógica vista em \"she must be asleep\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You ___ smoke in here when I was a kid — it was totally normal back then.\" Complete with the modal indicating that an action was permitted in the past, but no longer is:",
    opcoes: ["would", "should", "must", "could", "can"],
    correta: 3,
    explicacao: "\"Could\" também é usado para indicar que algo era permitido no passado, mas não é mais — fumar em ambientes internos era comum antigamente. Esse sentido de \"permissão passada\" soma-se aos já vistos de habilidade e possibilidade fraca.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"Can I borrow your pen for a second?\" \"Sure, you ___.\" Complete the informal response granting permission:",
    opcoes: ["must", "shall", "should", "would", "can"],
    correta: 4,
    explicacao: "\"Can\" é usado tanto para pedir quanto para conceder permissão de forma simples e cotidiana — \"você pode\". É a resposta mais natural e comum ao pedido informal feito com \"can I...?\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"You ___ be very careful when crossing this street — it's dangerous.\" Complete with the modal expressing strong obligation for safety:",
    opcoes: ["must", "could", "should", "might", "would"],
    correta: 0,
    explicacao: "\"Must\" expressa uma obrigação forte relacionada à segurança, mais enfática que um simples conselho (\"should\"). O adjetivo \"dangerous\" reforça a urgência que justifica o uso de \"must\" em vez de \"should\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"I'm not sure, but the meeting ___ be cancelled due to the storm.\" Complete with the modal expressing moderate possibility:",
    opcoes: ["must", "may", "should", "can't", "needn't"],
    correta: 1,
    explicacao: "\"May\" expressa possibilidade moderada, incerta — coerente com \"I'm not sure\". É semelhante a \"might\", mas ligeiramente mais assertivo quanto à chance de a reunião ser cancelada.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"He shouldn't have spent all his savings on that car.\" A estrutura indica que gastar as economias foi, na avaliação de quem fala:",
    opcoes: ["obrigatório", "uma boa decisão", "um erro, algo que não deveria ter acontecido", "impossível de acontecer", "um hábito antigo"],
    correta: 2,
    explicacao: "\"Shouldn't have + particípio\" expressa crítica a uma ação passada considerada errada — gastar todas as economias no carro é visto como um erro de julgamento. É o par negativo de \"should have\", que indica algo que não foi feito mas deveria ter sido.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"___ we start the meeting now, or should we wait for everyone?\" Complete with the modal used to suggest an action:",
    opcoes: ["Must", "Need", "Would", "Shall", "Might"],
    correta: 3,
    explicacao: "\"Shall we...?\" é uma estrutura clássica para fazer sugestões coletivas, especialmente na primeira pessoa do plural. É diferente de \"must we\", que soaria como uma pergunta sobre obrigação, não sobre iniciar algo juntos.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"This suitcase is so heavy — I ___ barely lift it!\" Complete with the modal expressing (in)ability in the present:",
    opcoes: ["should", "must", "would", "shall", "can"],
    correta: 4,
    explicacao: "\"Can\" (aqui com \"barely\", quase não) expressa a capacidade limitada de levantar a mala pesada. \"Can barely\" é uma combinação comum para indicar que uma ação é feita com muita dificuldade.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ apologize to her — it wasn't really your fault.\" Complete with the modal indicating that an apology, while possible, isn't strictly necessary:",
    opcoes: ["needn't", "must", "mustn't", "shan't", "can't"],
    correta: 0,
    explicacao: "\"Needn't\" indica que a ação não é necessária, sem proibi-la — a pessoa pode se desculpar se quiser, mas não é obrigada, já que a culpa não foi totalmente dela. É diferente de \"mustn't\", que proibiria o pedido de desculpas.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"Given his talent, he ___ have become a professional musician if he had pursued it.\" Complete with the modal + perfect expressing a hypothetical past possibility that didn't happen:",
    opcoes: ["should", "could", "must", "shall", "needn't"],
    correta: 1,
    explicacao: "\"Could have + particípio\" expressa uma possibilidade hipotética no passado que não se concretizou — ele tinha talento para se tornar músico profissional, mas não seguiu esse caminho. É diferente de \"should have\", que traria julgamento de que ele deveria ter feito isso.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"Visitors ___ not feed the animals at the zoo.\" Complete with the modal expressing a formal prohibition, typical of signs and rules:",
    opcoes: ["may", "would", "must", "should", "need"],
    correta: 2,
    explicacao: "\"Must not\" é a forma padrão de proibição em placas e regulamentos — \"os visitantes não devem alimentar os animais\". É mais forte e formal que \"shouldn't\", adequado ao tom de regra institucional de um zoológico.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"___ you like some coffee?\" Complete with the modal used in a polite offer:",
    opcoes: ["Must", "Should", "Can", "Would", "Shall"],
    correta: 3,
    explicacao: "\"Would you like...?\" é a estrutura padrão para fazer oferecimentos educados, muito mais comum que \"do you want\" em contextos formais ou de cortesia, como oferecer café a um convidado.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"I ___ rather stay home tonight than go to the party.\" Complete with the fixed modal expression of preference:",
    opcoes: ["must", "should", "can", "shall", "would"],
    correta: 4,
    explicacao: "\"Would rather\" é uma expressão fixa para indicar preferência entre duas opções, seguida do verbo na forma base (\"would rather stay... than go\"). Não deve ser confundida com \"had better\", que expressa conselho forte, não preferência.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You ___ be joking — there's no way you won the lottery!\" Complete with the modal expressing strong disbelief:",
    opcoes: ["must", "shan't", "mustn't", "needn't", "would"],
    correta: 0,
    explicacao: "\"Must\" aqui expressa uma conclusão irônica de incredulidade — \"você só pode estar brincando\". É o mesmo uso dedutivo do modal, aplicado a uma situação de surpresa e ceticismo, não de obrigação literal.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"Employees ___ arrive at least ten minutes before their shift starts.\" Complete with the modal expressing a workplace rule:",
    opcoes: ["might", "must", "could", "would", "used to"],
    correta: 1,
    explicacao: "\"Must\" expressa uma regra obrigatória do ambiente de trabalho — chegar dez minutos antes do turno. É o mesmo uso de obrigação visto com leis e regulamentos, aplicado agora a uma norma de empresa.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"He is very talented — he ___ paint beautifully since he was a child.\" Complete with the modal expressing a long-standing ability:",
    opcoes: ["should", "must", "could", "shall", "would"],
    correta: 2,
    explicacao: "\"Could\" expressa uma habilidade que a pessoa desenvolveu e manteve desde criança — pintar bem. É o mesmo sentido de capacidade visto em \"could swim\" e \"could climb trees\", aplicado aqui a um talento artístico.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"You ___ take an umbrella, just in case — it looks like it might rain.\" Complete with the modal that gives a mild, optional suggestion:",
    opcoes: ["must", "mustn't", "shan't", "might want to", "needn't"],
    correta: 3,
    explicacao: "\"Might want to\" é uma forma suave e indireta de sugestão, mais branda que \"should\", frequentemente usada para dar conselhos sem soar impositivo. \"Just in case\" reforça o tom de precaução opcional, não de obrigação.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"In the 1950s, families ___ often gather around the radio in the evening.\" Complete with the modal expressing a repeated habit in the past:",
    opcoes: ["must", "should", "can", "may", "would"],
    correta: 4,
    explicacao: "\"Would\", combinado com \"often\", descreve um hábito repetido numa época passada — famílias se reunindo ao redor do rádio nos anos 1950. É o mesmo uso visto com \"every summer, my grandfather would take us fishing\".",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ be starving — you haven't eaten all day!\" Complete with the modal expressing a confident deduction:",
    opcoes: ["must", "could", "might", "may", "would"],
    correta: 0,
    explicacao: "\"Must\", de novo em sentido dedutivo, expressa uma conclusão quase certa a partir de uma evidência clara — não ter comido o dia todo indica fome. É diferente de \"might/could/may\", que trariam um grau menor de certeza.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"___ I ask you a personal question?\" Complete with the modal used to politely ask permission before something potentially sensitive:",
    opcoes: ["Must", "May", "Shall", "Would", "Need"],
    correta: 1,
    explicacao: "\"May I...?\" é a forma mais formal e educada de pedir permissão, apropriada antes de uma pergunta pessoal, que exige cuidado e cortesia. \"Can I\" também seria aceitável, mas \"may\" carrega o tom mais formal que a situação sugere.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "media",
    enunciado: "\"You ___ be more careful with your money — you're always broke by the middle of the month.\" Complete with the modal used for a recurring piece of advice:",
    opcoes: ["should", "shall", "need", "will", "can"],
    correta: 0,
    explicacao: "\"Should\" continua sendo o modal de conselho, aqui aplicado a um padrão recorrente de comportamento (ficar sem dinheiro todo mês). O tom permanece de sugestão, não de ordem — coerente com o uso mais comum desse modal.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "facil",
    enunciado: "\"Sorry, I ___ come to your party — I already have plans that night.\" Complete with the modal expressing inability due to a prior commitment:",
    opcoes: ["can't", "mustn't", "shouldn't", "needn't", "shan't"],
    correta: 0,
    explicacao: "\"Can't\" expressa a impossibilidade de comparecer, por já ter outro compromisso — um uso comum de recusa educada. \"Mustn't\" soaria como proibição, sentido diferente de simplesmente não poder ir por falta de disponibilidade.",
  },
  {
    materia: "ingles", tema: "Modal verbs", dificuldade: "dificil",
    enunciado: "\"He must have missed the bus — he's never this late otherwise.\" A estrutura \"must have + particípio\" expressa:",
    opcoes: ["uma obrigação passada", "uma dedução sobre o passado, com base em evidências", "um pedido educado", "uma proibição passada", "um hábito repetido"],
    correta: 1,
    explicacao: "\"Must have + particípio\" é usado para deduções sobre o passado — concluir, a partir de evidências (o atraso incomum), que algo provavelmente aconteceu (perder o ônibus). É a versão no passado do \"must\" dedutivo já visto em \"she must be asleep\".",
  },
];
