/* Questões autorais de Inglês — Conditionals. */

export const questoes = [
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If it rains, we ___ the trip.\" Complete with the correct verb form for a zero conditional (general truth/habit):",
    opcoes: ["cancel", "will cancel", "would cancel", "canceled", "had cancelled"],
    correta: 0,
    explicacao: "O zero conditional descreve verdades gerais ou hábitos, usando simple present nas duas orações (\"if it rains, we cancel\"). É usado quando a consequência é automática e sempre verdadeira, não uma previsão específica sobre um evento futuro único.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you heat ice, it ___.\" Complete with the correct zero conditional form (scientific fact):",
    opcoes: ["will melt", "melts", "would melt", "melted", "had melted"],
    correta: 1,
    explicacao: "Fatos científicos usam o zero conditional, com simple present em ambas as orações — \"se você aquece gelo, ele derrete\" é sempre verdade, não uma previsão única. É a mesma estrutura de \"if it rains, we cancel\".",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If I have time tomorrow, I ___ visit you.\" Complete with the correct first conditional form (real, possible future situation):",
    opcoes: ["visit", "would visit", "will visit", "visited", "would have visited"],
    correta: 2,
    explicacao: "O first conditional descreve uma condição real e possível no futuro, com simple present na oração \"if\" e \"will\" + verbo na oração principal. \"Tomorrow\" confirma que se trata de uma possibilidade concreta, não hipotética.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If she studies hard, she ___ the exam.\" Complete with the correct first conditional form:",
    opcoes: ["passed", "passes", "would pass", "will pass", "will have passed"],
    correta: 3,
    explicacao: "Segue a mesma estrutura do first conditional: \"if\" + simple present, oração principal com \"will\" + verbo. Estudar bastante é uma condição real e alcançável, coerente com esse tipo de condicional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I won the lottery, I ___ around the world.\" Complete with the correct second conditional form (hypothetical, unlikely situation):",
    opcoes: ["travel", "will travel", "would have traveled", "traveled", "would travel"],
    correta: 4,
    explicacao: "O second conditional descreve uma situação hipotética, improvável ou puramente imaginária no presente/futuro, com simple past na oração \"if\" e \"would\" + verbo na principal. Ganhar na loteria é hipotético, diferente de uma condição real e possível do first conditional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If I ___ you, I would apologize.\" Complete with the correct second conditional form:",
    opcoes: ["were", "was", "am", "will be", "had been"],
    correta: 0,
    explicacao: "No second conditional, o verbo \"to be\" costuma usar \"were\" para todas as pessoas (inclusive \"I\" e \"he/she/it\"), mesmo em inglês informal — é a chamada \"subjunctive form\". \"If I were you\" é a expressão fixa mais comum desse tipo de condicional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I had studied harder, I ___ the exam.\" Complete with the correct third conditional form (hypothetical past that didn't happen):",
    opcoes: ["pass", "would have passed", "would pass", "will pass", "passed"],
    correta: 1,
    explicacao: "O third conditional fala de uma condição hipotética no passado que não aconteceu, com past perfect na oração \"if\" e \"would have\" + particípio na principal — \"se eu tivesse estudado mais, eu teria passado\", mas não estudou e não passou. É usado para lamentar decisões passadas.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If they had left earlier, they ___ the traffic.\" Complete with the correct third conditional form:",
    opcoes: ["avoid", "will avoid", "would have avoided", "would avoid", "avoided"],
    correta: 2,
    explicacao: "Mantém a estrutura do third conditional: past perfect (\"had left\") na condicional, \"would have avoided\" na principal — uma consequência hipotética de uma condição passada que não se cumpriu, já que eles não saíram mais cedo.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If you don't water the plants, they ___.\" Complete with the correct zero conditional form:",
    opcoes: ["died", "will die", "would die", "die", "would have died"],
    correta: 3,
    explicacao: "É uma verdade geral sobre plantas, expressa no zero conditional — simple present em ambas as orações. Não se trata de uma previsão sobre uma planta específica, mas de uma regra sempre válida.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"Unless you hurry, you ___ the bus.\" Complete with the correct first conditional form (\"unless\" = \"if...not\"):",
    opcoes: ["miss", "would have missed", "would miss", "missed", "will miss"],
    correta: 4,
    explicacao: "\"Unless\" equivale a \"if...not\" (\"if you don't hurry\"), mas continua exigindo a estrutura do first conditional na oração principal: \"will\" + verbo. É uma condição real sobre um evento futuro próximo.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If she were taller, she ___ a professional basketball player.\" Complete with the correct second conditional form:",
    opcoes: ["would be", "will be", "was", "is", "would have been"],
    correta: 0,
    explicacao: "A altura de uma pessoa não é algo que muda facilmente, então essa é uma condição hipotética e improvável sobre o presente — pede o second conditional (\"would be\"). Diferente do third conditional, que trataria de um evento único no passado.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If I ___ more money, I would buy a new car.\" Complete with the correct second conditional form:",
    opcoes: ["have", "had", "will have", "having", "have had"],
    correta: 1,
    explicacao: "O second conditional usa simple past na oração \"if\" (\"had\"), mesmo com sentido presente/futuro hipotético. \"Would buy\" na principal confirma que se trata desse tipo de condicional, e não do first ou third.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I hadn't missed the flight, I ___ late for the conference.\" Complete with the correct third conditional form:",
    opcoes: ["am not", "won't be", "wouldn't have been", "wasn't", "wouldn't be"],
    correta: 2,
    explicacao: "\"Hadn't missed\" (past perfect negativo) na condicional pede \"wouldn't have been\" (would have + not + particípio) na principal — uma consequência hipotética negada de um evento passado que realmente aconteceu (ele perdeu o voo).",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If you mix blue and yellow, you ___ green.\" Complete with the correct zero conditional form:",
    opcoes: ["got", "will get", "would get", "get", "would have gotten"],
    correta: 3,
    explicacao: "Misturar azul e amarelo sempre resulta em verde — uma verdade constante, própria do zero conditional com simple present nas duas orações.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If we leave now, we ___ the traffic.\" Complete with the correct first conditional form:",
    opcoes: ["avoid", "would have avoided", "would avoid", "avoided", "will avoid"],
    correta: 4,
    explicacao: "Sair agora é uma condição real e ainda possível de cumprir — pede o first conditional, com \"will avoid\" na oração principal, diferente da situação já perdida do third conditional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"I would have called you if I ___ your number.\" Complete with the correct third conditional form:",
    opcoes: ["had", "have", "have had", "would have", "will have"],
    correta: 0,
    explicacao: "A oração \"if\" do third conditional usa past perfect (\"had had\" seria \"tivesse tido\"), mas aqui apenas \"had\" (\"had your number\") já forma o past perfect do verbo \"to have\" nesse contexto — \"se eu tivesse seu número\". A oração principal já veio no \"would have called\", confirmando o tipo de condicional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you don't feel well, you ___ see a doctor.\" Complete with the correct first conditional form (advice framed as consequence):",
    opcoes: ["would", "should", "will", "must", "shall"],
    correta: 1,
    explicacao: "Embora a maioria dos exemplos de first conditional use \"will\", a oração principal também pode usar outros modais como \"should\", \"can\" ou \"must\" no lugar de \"will\", mantendo o mesmo sentido de condição real — aqui, um conselho como consequência de não se sentir bem.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If you don't practice, you ___ improve.\" Complete with the correct first conditional form (negative result):",
    opcoes: ["don't", "wouldn't", "won't", "didn't", "hadn't"],
    correta: 2,
    explicacao: "\"Won't\" (will not) é a forma negativa do first conditional, indicando que, sem prática, a melhora não vai acontecer. Mantém a estrutura \"if\" + simple present / \"will not\" + verbo.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If I ___ a bird, I would fly around the world.\" Complete with the correct second conditional form (impossible situation):",
    opcoes: ["am", "was", "will be", "were", "had been"],
    correta: 3,
    explicacao: "Ser um pássaro é uma situação impossível, tratada com o second conditional e a forma \"were\" para todas as pessoas — o mesmo padrão de \"if I were you\". Situações impossíveis (não apenas improváveis) também usam essa estrutura.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If the company had invested in new technology, it ___ more competitive today.\" Complete with the correct mixed conditional form (past condition, present result):",
    opcoes: ["is", "would have been", "will be", "was", "would be"],
    correta: 4,
    explicacao: "Este é um mixed conditional: a condição está no passado (\"had invested\", past perfect), mas o resultado é sentido no presente (\"today\"), o que pede \"would be\" (sem \"have\") em vez de \"would have been\". É uma combinação avançada entre o second e o third conditional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you heat water to 100°C, it ___.\" Complete with the correct zero conditional form:",
    opcoes: ["boils", "will boil", "would boil", "boiled", "would have boiled"],
    correta: 0,
    explicacao: "Mais um exemplo de fato científico com zero conditional — simple present nas duas orações, já que a água sempre ferve a 100°C ao nível do mar, independentemente de quando a frase é dita.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If it snows tomorrow, schools ___ closed.\" Complete with the correct first conditional form:",
    opcoes: ["are", "will be", "would be", "were", "have been"],
    correta: 1,
    explicacao: "Neve amanhã é uma condição real e possível — pede o first conditional, com \"will be\" na oração principal. É a mesma lógica de \"if it rains, we will cancel\", mas com o verbo \"to be\".",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"What would you do if you ___ a ghost?\" Complete with the correct second conditional form:",
    opcoes: ["see", "will see", "saw", "have seen", "had seen"],
    correta: 2,
    explicacao: "Ver um fantasma é uma situação hipotética, improvável — pede o second conditional com simple past (\"saw\") na oração condicional. A pergunta com \"would you do\" já confirma o tipo de condicional esperado na resposta.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If humans didn't need oxygen, life on Earth ___ completely different.\" Complete with the correct second conditional form (counterfactual general truth):",
    opcoes: ["is", "was", "will be", "would be", "would have been"],
    correta: 3,
    explicacao: "Apesar de tratar de algo permanentemente falso (humanos sempre precisam de oxigênio), a estrutura usada continua sendo o second conditional, porque descreve uma situação hipotética e contrafactual no presente, não um evento único no passado.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you press this button, the machine ___ off.\" Complete with the correct zero conditional form:",
    opcoes: ["would have turned", "will turn", "would turn", "turned", "turns"],
    correta: 4,
    explicacao: "Descreve o funcionamento constante de uma máquina — sempre que o botão é pressionado, ela desliga. É uma instrução/regra de funcionamento, típica do zero conditional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If I see him, I ___ him your message.\" Complete with the correct first conditional form:",
    opcoes: ["will give", "give", "would give", "gave", "would have given"],
    correta: 0,
    explicacao: "Encontrar a pessoa é uma condição real e possível — first conditional, com \"will give\" na oração principal, seguindo a estrutura padrão \"if\" + simple present / \"will\" + verbo.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I had known you were coming, I ___ a cake.\" Complete with the correct third conditional form:",
    opcoes: ["bake", "would have baked", "would bake", "will bake", "baked"],
    correta: 1,
    explicacao: "\"Had known\" (past perfect) na condicional, combinado com \"would have baked\" na principal, forma o third conditional clássico — uma consequência hipotética de algo que não aconteceu no passado (a pessoa não sabia e, por isso, não fez o bolo).",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you don't leave now, you ___ late.\" Complete with the correct first conditional form:",
    opcoes: ["are", "would be", "will be", "were", "have been"],
    correta: 2,
    explicacao: "Uma condição real sobre o presente imediato/futuro próximo — sair agora ou não — pede o first conditional, com \"will be\" na oração principal.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"I wouldn't have gotten the job if my friend ___ me the tip about the opening.\" Complete with the correct third conditional form:",
    opcoes: ["doesn't give", "didn't give", "won't give", "hadn't given", "isn't giving"],
    correta: 3,
    explicacao: "A oração principal já está no \"wouldn't have gotten\" (third conditional), então a condicional precisa do past perfect negativo, \"hadn't given\" — \"se meu amigo não tivesse me dado a dica\". A frase lamenta uma condição passada que, na realidade, aconteceu (ele deu a dica, e por isso ela conseguiu o emprego).",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you don't set an alarm, you ___ oversleep.\" Complete with the correct first conditional form:",
    opcoes: ["can", "would", "must", "should", "might"],
    correta: 4,
    explicacao: "Assim como \"should\" pode substituir \"will\" na oração principal do first conditional, \"might\" também é possível quando a consequência é apenas provável, não certa — \"você pode acabar dormindo demais\", uma possibilidade, não uma certeza.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If plants don't get sunlight, they ___.\" Complete with the correct zero conditional form:",
    opcoes: ["die", "will die", "would die", "died", "would have died"],
    correta: 0,
    explicacao: "Mais uma verdade geral sobre biologia vegetal, expressa no zero conditional com simple present nas duas orações — sem luz solar, plantas sempre morrem.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If I were rich, I ___ travel the world every year.\" Complete with the correct second conditional form:",
    opcoes: ["will", "would", "did", "do", "had"],
    correta: 1,
    explicacao: "Ser rico é hipotético para quem fala — second conditional, com \"would\" na oração principal, coerente com \"if I were rich\" (simple past do verbo \"to be\" no sentido hipotético).",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If she hadn't moved to another city, we ___ still be friends today.\" Complete with the correct mixed conditional form (past condition, present result):",
    opcoes: ["will", "would have", "would", "were", "had been"],
    correta: 2,
    explicacao: "Outro exemplo de mixed conditional: a condição está no passado (\"hadn't moved\"), mas o resultado é sentido no presente (\"still... today\"), o que exige apenas \"would\" (sem \"have\") + verbo na principal, e não \"would have been\".",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you touch fire, you ___ burned.\" Complete with the correct zero conditional form:",
    opcoes: ["got", "will get", "would get", "get", "would have gotten"],
    correta: 3,
    explicacao: "Uma consequência física sempre verdadeira — tocar fogo sempre causa queimadura — pede o zero conditional, com simple present nas duas orações.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If I finish my work early, I ___ to the gym.\" Complete with the correct first conditional form:",
    opcoes: ["go", "would have gone", "would go", "went", "will go"],
    correta: 4,
    explicacao: "Terminar o trabalho cedo é uma condição real e possível hoje — first conditional, com \"will go\" na oração principal.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I ___ the truth back then, I would have told you immediately.\" Complete with the correct third conditional form:",
    opcoes: ["had known", "knew", "know", "will know", "would know"],
    correta: 0,
    explicacao: "A oração principal (\"would have told\") indica third conditional; a condicional exige o past perfect (\"had known\") — \"se eu tivesse sabido a verdade\", situação hipotética sobre um momento específico do passado que não se confirmou.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If metal is heated, it ___.\" Complete with the correct zero conditional form:",
    opcoes: ["will expand", "expands", "would expand", "expanded", "would have expanded"],
    correta: 1,
    explicacao: "Outra verdade científica constante — metal aquecido sempre se expande — pede o zero conditional com simple present.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If you don't back up your files, you ___ lose them.\" Complete with the correct first conditional form:",
    opcoes: ["would", "could", "can", "might have", "had"],
    correta: 2,
    explicacao: "\"Can\" também pode substituir \"will\" na oração principal do first conditional quando se quer expressar uma consequência possível, e não certa — \"você pode perder seus arquivos\" se não fizer backup.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"Were I in charge of this project, I would change the entire strategy.\" Essa frase é uma versão mais formal, com inversão, de qual estrutura condicional?",
    opcoes: ["zero conditional", "first conditional", "third conditional", "second conditional (\"If I were in charge...\")", "mixed conditional"],
    correta: 3,
    explicacao: "\"Were I...\" é uma inversão formal que substitui \"If I were...\", mantendo a estrutura do second conditional (situação hipotética no presente). Essa inversão sem \"if\" é comum em registros mais formais e escritos, e costuma aparecer em textos de leitura do ENEM.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"Had I known about the traffic, I would have left earlier.\" Essa frase é uma versão com inversão de qual estrutura condicional?",
    opcoes: ["zero conditional", "first conditional", "second conditional", "mixed conditional apenas", "third conditional (\"If I had known...\")"],
    correta: 4,
    explicacao: "\"Had I known...\" substitui \"If I had known...\", mantendo a estrutura do third conditional (condição hipotética não realizada no passado). É o mesmo tipo de inversão formal vista com \"Were I...\", só que aplicada ao past perfect.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you eat too much sugar, you ___ gain weight over time.\" Complete with the correct zero conditional form:",
    opcoes: ["can", "will", "would", "might", "shall"],
    correta: 0,
    explicacao: "No zero conditional, mesmo modais como \"can\" podem aparecer na oração principal para expressar uma consequência geralmente verdadeira, sem que isso mude a natureza atemporal da regra — comer muito açúcar tende a causar ganho de peso.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If I ___ enough money, I will buy that jacket next week.\" Complete with the correct first conditional form:",
    opcoes: ["had", "have", "will have", "having", "would have"],
    correta: 1,
    explicacao: "A oração \"if\" do first conditional usa simple present (\"have\"), mesmo se referindo a uma condição sobre a semana que vem. \"Will buy\", já presente na oração principal, confirma esse tipo de condicional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I hadn't taken that job offer, I wouldn't be living in this city now.\" Essa frase combina uma condição no passado com um resultado no presente. Esse tipo de estrutura é chamado de:",
    opcoes: ["zero conditional", "first conditional", "mixed conditional", "third conditional puro", "second conditional puro"],
    correta: 2,
    explicacao: "Quando a condição está no passado (\"hadn't taken\", past perfect) mas o resultado é sentido no presente (\"wouldn't be living... now\"), a estrutura é um mixed conditional — uma combinação entre o third e o second conditional.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you don't feed the cat, it ___ hungry.\" Complete with the correct zero conditional form:",
    opcoes: ["got", "will get", "would get", "gets", "would have gotten"],
    correta: 3,
    explicacao: "Consequência automática e sempre verdadeira — um gato sem comida sempre fica com fome — pede o zero conditional com simple present.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If she calls, ___ me know immediately.\" Complete with the correct imperative form used in the main clause of a first conditional:",
    opcoes: ["let's", "will let", "would let", "letting", "let"],
    correta: 4,
    explicacao: "O first conditional também pode usar o imperativo na oração principal em vez de \"will\", como uma instrução direta — \"let me know\" (avise-me), sem sujeito explícito. É um uso comum em pedidos e instruções cotidianas.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I ___ taller when I was younger, I would have joined the basketball team.\" Complete with the correct third conditional form:",
    opcoes: ["had been", "was", "were", "am", "would be"],
    correta: 0,
    explicacao: "A oração principal (\"would have joined\") confirma o third conditional, o que exige past perfect na condicional — \"had been\" (\"se eu tivesse sido mais alto\"), referindo-se a uma condição específica do passado que não se cumpriu.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If you don't submit the form by Friday, your application ___ rejected.\" Complete with the correct first conditional form:",
    opcoes: ["was", "is", "would be", "will be", "had been"],
    correta: 3,
    explicacao: "Não enviar o formulário até sexta é uma condição real sobre um prazo futuro — first conditional, com \"will be\" na oração principal, seguindo o padrão \"if\" + simple present.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "dificil",
    enunciado: "\"If I ___ a time machine, I would go back and change a few decisions.\" Complete with the correct second conditional form:",
    opcoes: ["have", "had", "will have", "would have", "having"],
    correta: 1,
    explicacao: "Ter uma máquina do tempo é impossível/hipotético — second conditional, com simple past na condicional (\"had\") e \"would go\" na principal, seguindo o mesmo padrão de \"if I won the lottery\".",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "facil",
    enunciado: "\"If you freeze water, it ___ into ice.\" Complete with the correct zero conditional form:",
    opcoes: ["turned", "would turn", "will turn", "had turned", "turns"],
    correta: 4,
    explicacao: "Mais uma verdade científica constante — água congelada sempre vira gelo — pede o zero conditional com simple present nas duas orações.",
  },
  {
    materia: "ingles", tema: "Conditionals", dificuldade: "media",
    enunciado: "\"If he apologizes, I ___ him.\" Complete with the correct first conditional form:",
    opcoes: ["forgave", "will forgive", "would forgive", "forgive", "would have forgiven"],
    correta: 1,
    explicacao: "Um pedido de desculpas ainda não feito, mas possível, é uma condição real — first conditional, com \"will forgive\" na oração principal.",
  },
];
