/* Questões autorais de Inglês — Passive voice. */

export const questoes = [
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The chef cooks the meal.\" Rewrite in the passive voice:",
    opcoes: ["The meal is cooked by the chef.", "The meal was cooked by the chef.", "The meal cooks by the chef.", "The chef is cooked by the meal.", "The meal is cooking by the chef."],
    correta: 0,
    explicacao: "Na voz passiva, o objeto da frase ativa (\"the meal\") vira sujeito, e o verbo é formado por \"to be\" no mesmo tempo da ativa + particípio passado (\"is cooked\"). O agente original vem introduzido por \"by\". Simple present ativo vira simple present passivo.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The company launched a new product last week.\" Rewrite in the passive voice:",
    opcoes: ["A new product is launched by the company last week.", "A new product was launched by the company last week.", "A new product launched by the company last week.", "A new product has launched by the company last week.", "A new product will be launched by the company last week."],
    correta: 1,
    explicacao: "O verbo \"launched\" está no simple past, então a passiva usa \"was/were\" + particípio: \"was launched\". \"Last week\" confirma o tempo passado, descartando as formas de presente e futuro.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"They are building a new bridge downtown.\" Rewrite in the passive voice:",
    opcoes: ["A new bridge builds downtown.", "A new bridge was built downtown.", "A new bridge is being built downtown.", "A new bridge has been built downtown.", "A new bridge will build downtown."],
    correta: 2,
    explicacao: "O present continuous ativo (\"are building\") vira \"is/are being\" + particípio na passiva (\"is being built\"), mantendo a ideia de ação em progresso.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"They have finished the project.\" Rewrite in the passive voice:",
    opcoes: ["The project is finished.", "The project was finished.", "The project is being finished.", "The project has been finished.", "The project had finished."],
    correta: 3,
    explicacao: "O present perfect ativo (\"have finished\") vira \"has/have been\" + particípio na passiva (\"has been finished\"), preservando a ideia de ação concluída com relevância no presente.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The manager will announce the results tomorrow.\" Rewrite in the passive voice:",
    opcoes: ["The results are announced by the manager tomorrow.", "The results will announce by the manager tomorrow.", "The results were announced by the manager tomorrow.", "The results have been announced by the manager tomorrow.", "The results will be announced by the manager tomorrow."],
    correta: 4,
    explicacao: "O simple future ativo (\"will announce\") vira \"will be\" + particípio na passiva (\"will be announced\"). É um erro comum esquecer o \"be\" depois de \"will\", como na alternativa que diz apenas \"will announce\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"Shakespeare wrote 'Hamlet'.\" Rewrite in the passive voice:",
    opcoes: ["'Hamlet' was written by Shakespeare.", "'Hamlet' is written by Shakespeare.", "'Hamlet' has written by Shakespeare.", "'Hamlet' was writing by Shakespeare.", "'Hamlet' is wrote by Shakespeare."],
    correta: 0,
    explicacao: "\"Wrote\" (simple past) vira \"was written\" na passiva — \"write/wrote/written\" é um verbo irregular, e é justamente o particípio (\"written\") que a passiva exige, não o passado simples (\"wrote\").",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Someone stole my bike last night.\" Rewrite in the passive voice, focusing on the bike:",
    opcoes: ["My bike stole last night.", "My bike was stolen last night.", "My bike is stolen last night.", "My bike has stolen last night.", "My bike was stealing last night."],
    correta: 1,
    explicacao: "Quando o agente da ação é desconhecido ou irrelevante (\"someone\"), a passiva costuma omiti-lo — \"my bike was stolen last night\", sem precisar de \"by someone\". É um dos usos mais naturais da voz passiva.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"They had already sold the tickets before we arrived.\" Rewrite in the passive voice:",
    opcoes: ["The tickets were already sold before we arrived.", "The tickets have already been sold before we arrived.", "The tickets had already been sold before we arrived.", "The tickets were already selling before we arrived.", "The tickets already sold before we arrived."],
    correta: 2,
    explicacao: "O past perfect ativo (\"had sold\") vira \"had been\" + particípio na passiva (\"had been sold\"), mantendo a ideia de que essa ação aconteceu antes de outra ação no passado (\"we arrived\").",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"People speak Portuguese in Brazil.\" Rewrite in the passive voice:",
    opcoes: ["Portuguese has spoken in Brazil.", "Portuguese was spoken in Brazil.", "Portuguese speaks in Brazil.", "Portuguese is spoken in Brazil.", "Portuguese is speaking in Brazil."],
    correta: 3,
    explicacao: "Assim como no exemplo do bicicleta roubada, o agente genérico (\"people\") normalmente desaparece na passiva — \"Portuguese is spoken in Brazil\" soa mais natural do que mencionar \"by people\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The teacher is correcting the exams.\" Rewrite in the passive voice:",
    opcoes: ["The exams are corrected by the teacher.", "The exams were corrected by the teacher.", "The exams being corrected by the teacher.", "The exams have been corrected by the teacher.", "The exams are being corrected by the teacher."],
    correta: 4,
    explicacao: "O present continuous ativo (\"is correcting\") vira \"are being\" + particípio na passiva (\"are being corrected\"), o mesmo padrão visto com a ponte sendo construída.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"You must submit the report by Friday.\" Rewrite in the passive voice:",
    opcoes: ["The report must be submitted by Friday.", "The report is submitted by Friday.", "The report must submit by Friday.", "The report must have submitted by Friday.", "The report was must submitted by Friday."],
    correta: 0,
    explicacao: "Com modais (\"must\"), a passiva usa \"must be\" + particípio (\"must be submitted\"), mantendo o modal intacto antes de \"be\". É uma estrutura comum em instruções formais e regulamentos.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Millions of people watched the World Cup final.\" Rewrite in the passive voice:",
    opcoes: ["The World Cup final is watched by millions of people.", "The World Cup final was watched by millions of people.", "The World Cup final has watched by millions of people.", "The World Cup final watched by millions of people.", "The World Cup final was watching by millions of people."],
    correta: 1,
    explicacao: "\"Watched\" (simple past) vira \"was watched\" na passiva, com o agente (\"by millions of people\") mantido porque é uma informação relevante — diferente dos exemplos com agente genérico omitido.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The company employs two thousand workers.\" Rewrite in the passive voice:",
    opcoes: ["Two thousand workers employ the company.", "Two thousand workers were employed by the company.", "Two thousand workers are employed by the company.", "Two thousand workers have employed the company.", "Two thousand workers are employing the company."],
    correta: 2,
    explicacao: "O simple present ativo (\"employs\") vira \"are employed\" na passiva, com o objeto (\"two thousand workers\") assumindo a posição de sujeito da frase.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"They will have completed the construction by December.\" Rewrite in the passive voice:",
    opcoes: ["The construction will be completed by December.", "The construction was completed by December.", "The construction has been completed by December.", "The construction will have been completed by December.", "The construction will have completed by December."],
    correta: 3,
    explicacao: "O future perfect ativo (\"will have completed\") vira \"will have been\" + particípio na passiva (\"will have been completed\"), preservando a ideia de conclusão antes de um prazo futuro.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The government is going to raise taxes next year.\" Rewrite in the passive voice:",
    opcoes: ["Taxes are going to raise next year.", "Taxes were going to be raised next year.", "Taxes are raised next year.", "Taxes will raise next year.", "Taxes are going to be raised next year."],
    correta: 4,
    explicacao: "\"Is going to\" + verbo vira \"is going to be\" + particípio na passiva (\"are going to be raised\"), mantendo a estrutura de futuro planejado com evidência presente.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The news surprised everyone.\" Rewrite in the passive voice, focusing on \"everyone\":",
    opcoes: ["Everyone was surprised by the news.", "Everyone is surprised by the news.", "Everyone has surprised by the news.", "Everyone surprised by the news.", "Everyone was surprising by the news."],
    correta: 0,
    explicacao: "\"Surprised\" no simple past ativo vira \"was surprised\" na passiva, com \"everyone\" como novo sujeito e \"the news\" introduzido por \"by\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The recipe requires two cups of flour.\" Rewrite in the passive voice:",
    opcoes: ["Two cups of flour were required by the recipe.", "Two cups of flour are required by the recipe.", "Two cups of flour require the recipe.", "Two cups of flour have required the recipe.", "Two cups of flour are requiring by the recipe."],
    correta: 1,
    explicacao: "\"Requires\" no simple present vira \"are required\" na passiva, com \"two cups of flour\" como sujeito. É comum omitir \"by the recipe\" em textos reais, mas a estrutura gramatical continua correta com ele.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"People say that he is the best player in the league.\" Rewrite using the impersonal passive with \"it\":",
    opcoes: ["It says that he is the best player in the league.", "He is said to the best player in the league.", "It is said that he is the best player in the league.", "It was said that he is the best player in the league.", "He is saying to be the best player in the league."],
    correta: 2,
    explicacao: "\"It is said that...\" é a estrutura passiva impessoal usada para relatar opiniões gerais ou boatos sem atribuir a fala a uma pessoa específica — muito comum em textos jornalísticos e de opinião.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The hurricane destroyed hundreds of homes.\" Rewrite in the passive voice:",
    opcoes: ["Hundreds of homes destroy by the hurricane.", "Hundreds of homes are destroyed by the hurricane.", "Hundreds of homes have destroyed by the hurricane.", "Hundreds of homes were destroyed by the hurricane.", "Hundreds of homes were destroying by the hurricane."],
    correta: 3,
    explicacao: "\"Destroyed\" no simple past vira \"were destroyed\" na passiva, mantendo o agente \"by the hurricane\", já que a causa do desastre é uma informação central na frase.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The museum displays ancient artifacts.\" Rewrite in the passive voice:",
    opcoes: ["Ancient artifacts display the museum.", "Ancient artifacts are displaying in the museum.", "Ancient artifacts were displayed in the museum.", "Ancient artifacts have displayed in the museum.", "Ancient artifacts are displayed in the museum."],
    correta: 4,
    explicacao: "\"Displays\" no simple present vira \"are displayed\" na passiva. Note a mudança de preposição: \"by\" seria usado para o agente da ação, mas \"in\" indica o local, já que o museu aqui funciona como contêiner, não como agente ativo típico.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"Someone should have warned us about the risk.\" Rewrite in the passive voice:",
    opcoes: ["We should have been warned about the risk.", "We should warn about the risk.", "We should be warned about the risk.", "We were warned about the risk.", "We should have warned about the risk."],
    correta: 0,
    explicacao: "\"Should have warned\" (modal + present perfect) vira \"should have been\" + particípio na passiva (\"should have been warned\"), a estrutura mais complexa de modal com perfeito na voz passiva.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Volunteers planted a thousand trees in the park.\" Rewrite in the passive voice, omitting the agent:",
    opcoes: ["A thousand trees plant in the park.", "A thousand trees were planted in the park.", "A thousand trees are planted in the park.", "A thousand trees have planted in the park.", "A thousand trees were planting in the park."],
    correta: 1,
    explicacao: "Quando o agente (\"volunteers\") não é o foco da informação, ele pode ser omitido na passiva — \"a thousand trees were planted in the park\" foca no resultado, não em quem plantou.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The award ceremony is held every year in April.\" O verbo \"is held\", nessa frase, está na voz:",
    opcoes: ["ativa, simple present", "passiva, simple past", "passiva, simple present", "ativa, present continuous", "passiva, present continuous"],
    correta: 2,
    explicacao: "\"Is held\" é \"to be\" (is) + particípio (held, de \"to hold\") no simple present — uma construção passiva típica para descrever eventos recorrentes organizados por terceiros, sem precisar nomear quem organiza.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"This song was written by a famous composer in the 1980s.\" Qual é o sujeito gramatical da frase na voz passiva?",
    opcoes: ["a famous composer", "the 1980s", "written", "this song", "was"],
    correta: 3,
    explicacao: "Na voz passiva, o sujeito gramatical é quem \"recebe\" a ação, não quem a pratica — \"this song\" é o sujeito, enquanto \"a famous composer\" é o agente, introduzido por \"by\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"The suspect is being questioned by the police right now.\" O tempo verbal da voz passiva usado nessa frase é:",
    opcoes: ["simple present passive", "past continuous passive", "present perfect passive", "simple past passive", "present continuous passive"],
    correta: 4,
    explicacao: "\"Is being questioned\" segue a estrutura \"is/are being\" + particípio, própria do present continuous na voz passiva — uma ação em progresso agora, mas vista do ponto de vista de quem sofre a ação (o suspeito).",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Two languages are spoken in this region: Spanish and Guarani.\" A frase está na voz passiva porque:",
    opcoes: ["o sujeito recebe a ação do verbo, sem precisar dizer quem fala as línguas", "o sujeito pratica a ação do verbo", "não há verbo principal", "o verbo está no gerúndio", "o verbo está no infinitivo"],
    correta: 0,
    explicacao: "Na voz passiva, o sujeito (\"two languages\") não pratica a ação de falar, mas a recebe — são faladas por pessoas que nem precisam ser mencionadas. É o mesmo padrão de agente omitido visto em \"Portuguese is spoken in Brazil\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The letter was sent yesterday.\" Rewrite in the active voice, using \"someone\" as the subject:",
    opcoes: ["Someone sends the letter yesterday.", "Someone sent the letter yesterday.", "Someone is sending the letter yesterday.", "Someone has sent the letter yesterday.", "Someone was sending the letter yesterday."],
    correta: 1,
    explicacao: "Para converter da passiva para a ativa, o particípio (\"sent\") volta à forma verbal correspondente ao tempo original — aqui, simple past (\"sent\"), já que a passiva estava em \"was sent\" (simple past passive).",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The bridge is being repaired.\" Rewrite in the active voice, using \"workers\" as the subject:",
    opcoes: ["Workers repair the bridge.", "Workers repaired the bridge.", "Workers are repairing the bridge.", "Workers have repaired the bridge.", "Workers will repair the bridge."],
    correta: 2,
    explicacao: "\"Is being repaired\" (present continuous passive) volta, na ativa, para \"are repairing\" (present continuous ativo) — o tempo verbal permanece o mesmo, apenas trocando quem é sujeito e quem é objeto.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"The novel has been translated into twenty languages.\" Rewrite in the active voice, using \"translators\" as the subject:",
    opcoes: ["Translators translate the novel into twenty languages.", "Translators translated the novel into twenty languages.", "Translators are translating the novel into twenty languages.", "Translators have translated the novel into twenty languages.", "Translators will have translated the novel into twenty languages."],
    correta: 3,
    explicacao: "\"Has been translated\" (present perfect passive) volta, na ativa, para \"have translated\" (present perfect ativo) — mantendo o mesmo tempo verbal, apenas invertendo sujeito e objeto.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Cars are manufactured in this factory.\" Qual verbo, entre as opções, completaria melhor a passiva \"Cars ___ in this factory\" mantendo o mesmo sentido e tempo?",
    opcoes: ["manufacture", "manufactured", "are manufacturing", "will manufacture", "are manufactured"],
    correta: 4,
    explicacao: "\"Are manufactured\" é a forma correta da voz passiva no simple present, coerente com o restante da frase dada como referência. As demais opções alterariam o tempo verbal ou a voz (ativa em vez de passiva).",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"This building was designed by a famous architect.\" A informação \"by a famous architect\" é chamada de:",
    opcoes: ["agente da passiva", "sujeito", "objeto direto", "complemento nominal apenas", "predicativo"],
    correta: 0,
    explicacao: "Na voz passiva, a expressão introduzida por \"by\" que indica quem praticou a ação é chamada de agente da passiva — equivale ao sujeito que a frase teria na voz ativa (\"a famous architect designed this building\").",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Not all passive sentences need to mention the agent.\" Em qual das frases abaixo omitir o agente com \"by\" é mais natural?",
    opcoes: ["\"The bridge was crossed by thousands of tourists.\"", "\"The Mona Lisa was painted ___.\"", "\"The award was given to her by the committee.\"", "\"The book was reviewed by a famous critic.\"", "\"The speech was written by the president's advisor.\""],
    correta: 1,
    explicacao: "Quando o agente é amplamente conhecido ou irrelevante para o sentido da frase (todo mundo sabe que foi Da Vinci), ele costuma ser omitido — \"the Mona Lisa was painted\" já basta. Nas outras opções, o agente traz informação nova e relevante, então normalmente é mantido.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"They offered her the job.\" (verbo com dois objetos) Rewrite in the passive voice, focusing on \"her\":",
    opcoes: ["Her was offered the job.", "She is offered the job.", "She was offered the job.", "The job was offered she.", "She has offered the job."],
    correta: 2,
    explicacao: "Verbos com dois objetos (\"offer her the job\") podem formar a passiva a partir do objeto indireto (\"her\" → \"she\", como sujeito) ou do objeto direto (\"the job was offered to her\"). Como sujeito, \"her\" precisa virar o pronome reto \"she\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"They offered her the job.\" Rewrite in the passive voice, focusing on \"the job\":",
    opcoes: ["The job has offer to her.", "The job offered to her.", "The job was offering to her.", "The job was offered to her.", "The job is offered she."],
    correta: 3,
    explicacao: "A mesma frase ativa também pode formar a passiva a partir do objeto direto (\"the job\"), exigindo a preposição \"to\" antes do objeto indireto (\"to her\") — \"the job was offered to her\".",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The engineers are testing the new bridge design.\" Rewrite in the passive voice:",
    opcoes: ["The new bridge design tests by the engineers.", "The new bridge design is tested by the engineers.", "The new bridge design has tested by the engineers.", "The new bridge design was tested by the engineers.", "The new bridge design is being tested by the engineers."],
    correta: 4,
    explicacao: "\"Are testing\" (present continuous ativo) vira \"is being tested\" (present continuous passivo), mantendo a ideia de teste em andamento no momento da fala.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The committee has rejected the proposal.\" Rewrite in the passive voice:",
    opcoes: ["The proposal has been rejected.", "The proposal was rejected.", "The proposal is rejected.", "The proposal is being rejected.", "The proposal had rejected."],
    correta: 0,
    explicacao: "\"Has rejected\" (present perfect ativo) vira \"has been rejected\" (present perfect passivo), preservando a relevância presente de uma decisão tomada recentemente.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"By the time we got there, someone had already cleaned the whole house.\" Rewrite the second clause in the passive voice:",
    opcoes: ["...the whole house was already cleaned.", "...the whole house had already been cleaned.", "...the whole house is already cleaned.", "...the whole house has already been cleaned.", "...the whole house was already being cleaned."],
    correta: 1,
    explicacao: "\"Had cleaned\" (past perfect ativo) vira \"had been cleaned\" (past perfect passivo), mantendo a ideia de que a limpeza já estava concluída antes da chegada — o mesmo padrão do exemplo dos ingressos já vendidos.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"Scientists have discovered a new species of frog.\" Rewrite in the passive voice:",
    opcoes: ["A new species of frog is discovered.", "A new species of frog was discovered.", "A new species of frog has been discovered.", "A new species of frog is being discovered.", "A new species of frog had discovered."],
    correta: 2,
    explicacao: "\"Have discovered\" (present perfect ativo) vira \"has been discovered\" (present perfect passivo, concordando com o sujeito singular \"a new species\"), mantendo a relevância presente da descoberta.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The waiter serves the customers quickly.\" Rewrite in the passive voice:",
    opcoes: ["The customers have served quickly by the waiter.", "The customers were served quickly by the waiter.", "The customers serve quickly by the waiter.", "The customers are served quickly by the waiter.", "The customers are serving quickly by the waiter."],
    correta: 3,
    explicacao: "\"Serves\" no simple present vira \"are served\" na passiva, com o advérbio \"quickly\" mantendo sua posição, geralmente após o verbo principal.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The judges will evaluate the contestants tomorrow.\" Rewrite in the passive voice:",
    opcoes: ["The contestants evaluate tomorrow.", "The contestants are evaluated tomorrow.", "The contestants were evaluated tomorrow.", "The contestants will evaluate tomorrow.", "The contestants will be evaluated tomorrow."],
    correta: 4,
    explicacao: "\"Will evaluate\" (simple future ativo) vira \"will be evaluated\" (simple future passivo), mantendo o \"be\" indispensável depois de \"will\" em qualquer construção passiva no futuro.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"People believe that the ancient city was destroyed by an earthquake.\" Rewrite using the impersonal passive with \"it\":",
    opcoes: ["It is believed that the ancient city was destroyed by an earthquake.", "It believes that the city was destroyed by an earthquake.", "The ancient city is believed that it was destroyed by an earthquake.", "It was believe that the ancient city destroyed by an earthquake.", "The ancient city believes it was destroyed by an earthquake."],
    correta: 0,
    explicacao: "\"It is believed that...\" segue o mesmo padrão impessoal de \"it is said that...\", usado para relatar crenças ou teorias amplamente aceitas sem atribuí-las a uma fonte específica.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The waiter is bringing the bill.\" Which sentence best explains why this is NOT in the passive voice?",
    opcoes: ["Porque o verbo está no gerúndio.", "Porque \"the waiter\" pratica a ação, não a recebe.", "Porque não há complemento.", "Porque o verbo está no infinitivo.", "Porque a frase é uma pergunta."],
    correta: 1,
    explicacao: "A voz passiva exige que o sujeito receba a ação, não a pratique. Em \"the waiter is bringing the bill\", o garçom é quem traz a conta — ele pratica a ação, então a frase está na voz ativa, apesar de usar \"is\" + verbo com -ing (present continuous, não passiva).",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The instructions must be followed carefully.\" Nessa frase passiva, o agente da ação foi:",
    opcoes: ["mencionado explicitamente com \"by\"", "colocado antes do verbo \"must\"", "omitido, por ser óbvio ou desnecessário", "transformado em sujeito", "substituído por \"it\""],
    correta: 2,
    explicacao: "O agente (quem deve seguir as instruções) foi omitido porque é genérico ou óbvio no contexto — não importa quem especificamente, e sim que as instruções sejam seguidas. É um uso muito comum da passiva em manuais e regras.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The cake was made with love by my grandmother.\" Qual é o objeto direto da frase na voz ativa correspondente (\"My grandmother made the cake with love\")?",
    opcoes: ["my grandmother", "made", "with love", "the cake", "was"],
    correta: 3,
    explicacao: "Na frase ativa \"my grandmother made the cake\", \"the cake\" é o objeto direto — e é exatamente ele que se torna o sujeito da voz passiva (\"the cake was made\"), num processo típico de transformação ativa-passiva.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"The contract needs to be signed before Monday.\" O verbo \"to be signed\" está na forma:",
    opcoes: ["infinitivo ativo", "imperativo passivo", "gerúndio passivo", "particípio ativo", "infinitivo passivo"],
    correta: 4,
    explicacao: "\"To be signed\" é um infinitivo na voz passiva (\"to be\" + particípio), usado depois de verbos como \"need to\", \"want to\" e \"have to\" quando o sujeito recebe a ação em vez de praticá-la — o contrato não assina, ele é assinado.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The mystery has never been solved.\" Rewrite in the active voice, using \"nobody\" as the subject:",
    opcoes: ["Nobody has solved the mystery.", "Nobody solves the mystery.", "Nobody solved the mystery.", "Nobody is solving the mystery.", "Nobody had solved the mystery."],
    correta: 0,
    explicacao: "\"Has never been solved\" (present perfect passive) volta, na ativa, para \"has never solved\" — como o sujeito muda para \"nobody\", a frase se torna \"nobody has solved the mystery\", mantendo o present perfect.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "media",
    enunciado: "\"The letters are delivered every morning by the mail carrier.\" Qual verbo, na frase, está na voz passiva?",
    opcoes: ["delivered, sozinho", "are delivered", "delivered by", "every morning", "the mail carrier"],
    correta: 1,
    explicacao: "\"Are delivered\" é a construção passiva completa: \"to be\" (are) + particípio (delivered). \"Delivered\" isolado não forma a passiva — precisa do auxiliar \"to be\" para funcionar como tal.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"The new rules were explained to all employees.\" Rewrite in the active voice, using \"the manager\" as the subject:",
    opcoes: ["The manager explains the new rules to all employees.", "The manager explained the new rules to all employees.", "The manager is explaining the new rules to all employees.", "The manager has explained the new rules to all employees.", "The manager will explain the new rules to all employees."],
    correta: 1,
    explicacao: "\"Were explained\" (simple past passive) volta, na ativa, para \"explained\" (simple past ativo), com \"the manager\" assumindo o papel de sujeito que pratica a ação.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "dificil",
    enunciado: "\"The vaccine is being tested on volunteers before it can be approved.\" Quantas construções passivas há nessa frase?",
    opcoes: ["nenhuma", "uma", "duas", "três", "quatro"],
    correta: 2,
    explicacao: "Há duas construções passivas: \"is being tested\" (present continuous passive) e \"be approved\" (infinitivo passivo, depois do modal \"can\"). Reconhecer múltiplas passivas na mesma frase é comum em textos científicos e jornalísticos mais longos.",
  },
  {
    materia: "ingles", tema: "Passive voice", dificuldade: "facil",
    enunciado: "\"Fresh bread is baked here every morning.\" Rewrite in the active voice, using \"the bakers\" as the subject:",
    opcoes: ["The bakers bake fresh bread here every morning.", "The bakers baked fresh bread here every morning.", "The bakers are baking fresh bread here every morning.", "The bakers have baked fresh bread here every morning.", "The bakers will bake fresh bread here every morning."],
    correta: 0,
    explicacao: "\"Is baked\" (simple present passive) volta, na ativa, para \"bake\" (simple present ativo, com -s eliminado porque o novo sujeito \"the bakers\" está no plural).",
  },
];
